version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      # Caching root node_modules since they don't change often
          - restore_cache:
              keys:
                - node_modules_root-{{ arch }}-{{ checksum "package.json" }}

          - run: yarn
          - save_cache:
              key: node_modules_root-{{ arch }}-{{ checksum "package.json" }}
              paths:
                - node_modules

          # # run tests!
          # - run: yarn generate-schema
          # - run: yarn lint-ci
          # - run: yarn flow-web
          # - run: yarn flow-native
          # - run: yarn test-frontend-ci
          # - run: yarn test-backend